# Advantages: Numpy Array Over List

   ### Save Coding Time
```python
    - No for loops: many vector and matrix operations save coding time
        Example:
        # python list
        my_list = [1,2,3]
        for i in range(len(my_list)):
            my_list[i] *= 3
        print("python for loop => ",my_list)
        
        # Numpy array
        import numpy as np
        np_array = np.array([1,2,3])
        print('numpy output => ', np_array*3)
        
```
   ### Faster Execution
```python
    - single type for each field to avoid type checking
    - Uses contiguous blocks of memory
```

   ### Uses less memory
```python
    - Python List: an array of pointers to python objects,
        with 4B+ per pointers plus 16B+ for a numerical object, (uses metadata         for every object)
    - Numpy Array: No pointers; * type and itemsize is same for columns
    - Compact data types like uint8 and float16
```




![List vs Numpy](images/numpy_list.png)


In [2]:
import numpy as np
# declaration 
a = np.array([2,3,4])
print("Initiate Numpy => ",a)

# using list
my_list = [1,2,3]
for i in range(len(my_list)):
    my_list[i] *= 3
print("python for loop => ",my_list)

# using Numpy array

np_array = np.array([1,2,3])
print('numpy output => ', np_array*3)

# range functin
b = np.arange(1,12,2) # (start,end,step)
print('range function => ', b)

# linear Spaced Array
N = 12
c = np.linspace(1, 12, N) # (start, end, number of elements) => floating point array
print('Linear Spaced array => ',c)
# what is linear spaced array?
import matplotlib.pyplot as plt
y = np.zeros(N)
plt.xlim([0, 15])
plt.plot(c, y+2, 'o') # 'o' => orrange

NameError: name 'np' is not defined

In [ ]:
# reshape
c = c.reshape(3,4)
print('reshape output: \n',c,'\n')
print('size does not depend on shape. After reshaping size = ',c.size)
print('---\nshape = ',c.shape, 'data type = ', c.dtype)
print('item size = ', c.itemsize, ' byte (how much memory in byte)')

###### * Some console examples

```python
>>> a = np.array([(1,2,3),(4,5,6)]) 
>>> a
array([[1, 2, 3],
       [4, 5, 6]])
>>> a < 4 
array([[ True,  True,  True],
       [False, False, False]])
>>> a *3
array([[ 3,  6,  9],
       [12, 15, 18]])
>>> a = np.zeros((3,4),dtype=int) 
>>> a
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])
>>> a = np.ones((2,3))
>>> a
array([[1., 1., 1.],
       [1., 1., 1.]])
>>> a = np.ones(10)
>>> a
array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])
>>> a = np.random.random((3,5))
>>> a
array([[0.86582116, 0.29724897, 0.54702738, 0.85751898, 0.6457486 ],
       [0.50709285, 0.84785754, 0.82507784, 0.39390458, 0.61538597],
       [0.62747913, 0.84032029, 0.10426593, 0.78443683, 0.16058113]])
>>> np.set_printoptions(precision=2)
>>> a
array([[0.87, 0.3 , 0.55, 0.86, 0.65],
       [0.51, 0.85, 0.83, 0.39, 0.62],
       [0.63, 0.84, 0.1 , 0.78, 0.16]])
>>> a = np.random.randint(0,10,5) # (start, end, size)) 
>>> a
array([6, 0, 3, 8, 9])
>>> a = np.random.randint(0,10,(5,4)) # (start, end, size))  
>>> a
array([[6, 2, 8, 7],
       [8, 2, 4, 6],
       [4, 9, 3, 1],
       [6, 7, 5, 4],
       [4, 3, 0, 2]])
>>> a.sum()
91
>>> a[0].sum() 
23
>>> a.sum(axis=1)
array([23, 20, 17, 22,  9])
>>> a.sum(axis=0) 
array([28, 23, 20, 20])
>>> a.min
<built-in method min of numpy.ndarray object at 0x000002683C773F30>
>>> a.min()
0
>>> a.max()
9
>>> a.mean()
4.55
>>> a.var() # variance
6.0475
>>> a.std()
2.4591665254715878

# load array from text file
>>> data = np.loadtxt("data.txt", dtype=np.uint8, delimiter=",", skiprows=1)
>>> data                                                                      
array([[1, 2, 3],
       [1, 2, 3]], dtype=uint8)

# randomness and shuffles 
>>> a = np.arange(10)  
>>> a
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
>>> np.random.shuffle(a)      
>>> a
array([1, 0, 7, 6, 8, 9, 5, 2, 3, 4])
>>> np.random.choice(a)
7
>>> np.random.choice(a)
1
>>> np.random.random_integers(5,10,2) # (start, end, size)                      
array([5, 8])
>>> np.random.random_integers(5,10,(2,3)) # (start, end, size) 
array([[ 5,  9, 10],
       [ 8,  8,  5]])

```

###### Aknowledgement: 
Joe James